
from tkinter import *
from tkinter.ttk import *

# creating tkinter window 
root = Tk() 

p1 = PhotoImage(file = r"books/b1.png")
p2 = PhotoImage(file = r"books/b2.png")
p3 = PhotoImage(file = r"books/b3.png")
p4 = PhotoImage(file = r"books/b4.png")
p5 = PhotoImage(file = r"books/b5.png")
p6 = PhotoImage(file = r"books/b6.png")
p7 = PhotoImage(file = r"books/b7.png")
p8 = PhotoImage(file = r"books/b8.png")
p9 = PhotoImage(file = r"books/b9.png")
p10 = PhotoImage(file = r"books/b10.png")
photo1 = PhotoImage(file = r"rating/1.png")
photo2 = PhotoImage(file = r"rating/2.png")
photo3 = PhotoImage(file = r"rating/3.png")
photo4 = PhotoImage(file = r"rating/4.png")
photo5 = PhotoImage(file = r"rating/5.png")

# Resizing image to fit on button 
P1 = p1.subsample(1,1)
P2 = p2.subsample(1,1)
P3 = p3.subsample(1,1)
P4 = p4.subsample(1,1)
P5 = p5.subsample(1,1)
P6 = p6.subsample(1,1)
P7 = p7.subsample(1,1)
P8= p8.subsample(1,1)
P9 = p9.subsample(1,1)
P10 = p10.subsample(1,1)
photoimage1 = photo1.subsample(5,6)
photoimage2 = photo2.subsample(5,6)
photoimage3 = photo3.subsample(5,6)
photoimage4 = photo4.subsample(5,6)
photoimage5 = photo5.subsample(5,6)


Button(root, image = P1).grid(row=0,column=0)
Button(root, image = photoimage5).grid(row=1,column=0)
Button(root, image = P2).grid(row=0,column=1)
Button(root, image = photoimage2).grid(row=1,column=1)
Button(root, image = P3).grid(row=0,column=2)
Button(root, image = photoimage2).grid(row=1,column=2)
Button(root, image = P4).grid(row=0,column=3)
Button(root, image = photoimage4).grid(row=1,column=3)
Button(root, image = P5).grid(row=0,column=4)
Button(root, image = photoimage1).grid(row=1,column=4)
Button(root, image = P6).grid(row=0,column=5)
Button(root, image = photoimage3).grid(row=1,column=5)
Button(root, image = P7).grid(row=0,column=6)
Button(root, image = photoimage4).grid(row=1,column=6)
#Button(root, image = photoimage).grid(row=0,column=7)
#Button(root, image = photoimage5).grid(row=1,column=7)
#3,4 rows
Button(root, image = P8).grid(row=3,column=0)
Button(root, image = photoimage1).grid(row=4,column=0)
Button(root, image = P9).grid(row=3,column=1)
Button(root, image = photoimage2).grid(row=4,column=1)
Button(root, image = P10).grid(row=3,column=2)
Button(root, image = photoimage3).grid(row=4,column=2)
Button(root, image = P1).grid(row=3,column=3)
Button(root, image = photoimage4).grid(row=4,column=3)
Button(root, image = P3).grid(row=3,column=4)
Button(root, image = photoimage4).grid(row=4,column=4)
Button(root, image = P6).grid(row=3,column=5)
Button(root, image = photoimage3).grid(row=4,column=5)
Button(root, image = P9).grid(row=3,column=6)
Button(root, image = photoimage4).grid(row=4,column=6)
#Button(root, image = photoimage).grid(row=3,column=7)
#Button(root, image = photoimage5).grid(row=4,column=7)
#5,6 rows
Button(root, image = P4).grid(row=5,column=0)
Button(root, image = photoimage1).grid(row=6,column=0)
Button(root, image = P7).grid(row=5,column=1)
Button(root, image = photoimage2).grid(row=6,column=1)
Button(root, image = P2).grid(row=5,column=2)
Button(root, image = photoimage3).grid(row=6,column=2)
Button(root, image = P10).grid(row=5,column=3)
Button(root, image = photoimage4).grid(row=6,column=3)
Button(root, image = P5).grid(row=5,column=4)
Button(root, image = photoimage5).grid(row=6,column=4)
Button(root, image = P7).grid(row=5,column=5)
Button(root, image = photoimage3).grid(row=6,column=5)
Button(root, image = P3).grid(row=5,column=6)
Button(root, image = photoimage4).grid(row=6,column=6)
#Button(root, image = photoimage).grid(row=5,column=7)
#Button(root, image = photoimage5).grid(row=6,column=7)
root.state("zoomed")



mainloop() 
